#%RAML 1.0
title: Pokenest API
mediaType: application/json
types:
    Pokemon:
        type: object
        properties:
            id: number
            name: string
            last_encounter_time: datetime
            average_time_offset: number
            total_encounter_time: number
            encoutner_rate: number
    Encounter:
        type: object
        properties:
            lat: number
            lng: number
            pokemon_id: number
    Nest:
        type: object
        properties:
            lat: number
            lng: number
            geohash: string
            pokemon: Pokemon
/encounters:
    get:
        description: Return encounter of pokemons in last 24h on map
        queryParameters:
            pokemon_id: number
            swLat: number
            swLng: number
            neLat: number
            neLng: number
        responses:
            200:
                body:
                  application/json:
                    properties:
                      encounters: Encounter[]
/area:
    get:
        description: Get info of area in last 24h
        queryParameters:
            lat: number
            lng: number
        responses:
            200:
                body:
                  application/json:
                    properties: 
                        swLat: number
                        swLng: number
                        neLat: number
                        neLng: number
                        pokemons: Pokemon[]
/nests:
    get:
        description: Get nests of pokemon on map in last 24h (Exclude common pokemons)
        queryParameters:
            swLat: number
            swLng: number
            neLat: number
            neLng: number
        responses:
            200:
                body:
                  application/json:
                    properties:
                        nests: Nest[]
                
      